### ISSUE TITLE
Vote needs Session code

### ISSUE THREAD

**Issue by GTZL1** [heig-PRO-b04/java-backend#111]
The session code needs to be send in endpoint PUT /mod/{idModerator}/poll/{idPoll}/question/{idQuestion}/answer/{idAnswer}/vote.
This endpoint must become /mod/{idModerator}/poll/{idPoll}/session/{sessionCode}/question/{idQuestion}/answer/{idAnswer}/vote

**Comment by glsubri** [comment]
Why though ?

If you have the token given to you, you can find the associated session.
