### ISSUE TITLE
`indexInPoll` in `ServerQuestion` is a double

### ISSUE THREAD

**Issue by glsubri** [heig-PRO-b04/java-backend#170]
Is there any reason why the `indexInPoll` in `ServerQuestion.java` is a double ? Shouldn't it be a `int` ?

**Comment by GTZL1** [comment]
It's what Alex proposed: if you want to move a question between two others (let's say the 4 between 2 and 3), you just set his index to 2.5. This way you don't need to modify all others index :)

**Comment by glsubri** [comment]
Ok. Good idea. Should we specify that in the API as well then ?

**Comment by GTZL1** [comment]
Rather in the documentation instead of especially the API I think
