### ISSUE TITLE
Strings values cannot be longer than 255 characters

### ISSUE THREAD

**Issue by matt989253** [heig-PRO-b04/java-backend#190]
When creating a poll, a question, or an answer with a title (or any other string input) that is strictly longer than 255 characters, the backend sends a 404 error after trying to insert the value, and trying to send it back when it doesn't exist.
Stacktrace:
[stacktrace.txt](https://github.com/heig-PRO-b04/java-backend/files/4586831/stacktrace.txt)

**Comment by alexandrepiveteau** [comment]
Fixed in #231.
