### ISSUE TITLE
Change how authenticated endpoints work

### ISSUE THREAD

**Issue by alexandrepiveteau** [heig-PRO-b04/java-backend#42]
Currently, we're passing authentication tokens in the body of the http requests we're making. Conceptually, it would make more sense to distinguish the **data** from the **access control** information.

Therefore, I suggest that we instead pass authentication tokens as a query parameter. For instance, we might have the following queries :

- `https://api.rockin.app/login` (remains normal)
- `https://api.rockin.app/mod/123/poll/456?token=BASE64ENCODED`

The tokens will be encoded in base 64 before being passed as a query parameter.

**Comment by glsubri** [comment]
Why would we need to encode the token if they're already alphanumeric ?
