### ISSUE TITLE
@generatedvalue not possible

### ISSUE THREAD

**Issue by GTZL1** [heig-PRO-b04/java-backend#5]
I discovered that @generatedvalue cannot be used in composite IDs. This is a serious problem for our initial plans.
For now I chose to assign a parameter value to this id, which let us the possibility of making our own number generator.

**Comment by alexandrepiveteau** [comment]
While browsing a bit, I came along [this link](https://vladmihalcea.com/how-to-map-a-composite-identifier-using-an-automatically-generatedvalue-with-jpa-and-hibernate/). Could it be of any help ?

**Comment by alexandrepiveteau** [comment]
Since we've found a fix (see in particular #102 as an example) with `Transactional` insertions, we can close the issue for now.

Feel free to re-open it as needed.
